/**
 * Reactive Resume Template Metadata Registry
 * All 15 templates extracted from Reactive Resume, adapted for OpportunityX.
 * Each template maps to the existing OpportunityX Resume JSON schema.
 */

export const REACTIVE_TEMPLATE_METADATA = [
  {
    id: 'creative-sidebar',
    name: 'Creative Sidebar',
    description: 'Two-column with a bold colored sidebar and skill tags. Great for creative or tech roles where visual flair is welcome.',
    category: 'Creative',
    previewImage: '/templates/reactive/creative-sidebar.jpg',
    supportsPhoto: true,
    columns: 2,
    atsFriendly: false,
    supportsSidebar: true,
    sidebarPosition: 'left',
    recommendedFor: ['Creative', 'Tech', 'Design'],
    difficulty: 'Standard',
    tags: ['Two-column', 'Creative', 'Tech', 'Visual flair', 'Photo'],
    accentColor: '#F97316',
    colorVariants: ['#F97316', '#2563EB', '#7C3AED', '#059669', '#DC2626']
  },
  {
    id: 'professional-clean',
    name: 'Professional Clean',
    description: 'Two-column, clean and professional with subtle section dividers. Suits corporate, finance, or consulting positions.',
    category: 'Corporate',
    previewImage: '/templates/reactive/professional-clean.jpg',
    supportsPhoto: false,
    columns: 2,
    atsFriendly: true,
    supportsSidebar: false,
    sidebarPosition: 'none',
    recommendedFor: ['Corporate', 'Finance', 'Consulting'],
    difficulty: 'Standard',
    tags: ['Two-column', 'Clean', 'Professional', 'Corporate'],
    accentColor: '#2563EB',
    colorVariants: ['#2563EB', '#059669', '#7C3AED', '#F97316']
  },
  {
    id: 'marketing-accent',
    name: 'Marketing Accent',
    description: 'Two-column with soft header accent and circular profile photo. Ideal for marketing, HR, or client-facing roles.',
    category: 'Creative',
    previewImage: '/templates/reactive/marketing-accent.jpg',
    supportsPhoto: true,
    columns: 2,
    atsFriendly: false,
    supportsSidebar: true,
    sidebarPosition: 'right',
    recommendedFor: ['Marketing', 'HR', 'Client-facing'],
    difficulty: 'Standard',
    tags: ['Two-column', 'Soft accent', 'Marketing', 'HR', 'Photo'],
    accentColor: '#059669',
    colorVariants: ['#059669', '#F97316', '#2563EB', '#7C3AED']
  },
  {
    id: 'developer-dark',
    name: 'Developer Dark',
    description: 'Two-column with a dark teal sidebar and skills grid. Modern feel for developers, data scientists, or technical PMs.',
    category: 'Tech',
    previewImage: '/templates/reactive/developer-dark.jpg',
    supportsPhoto: false,
    columns: 2,
    atsFriendly: false,
    supportsSidebar: true,
    sidebarPosition: 'left',
    recommendedFor: ['Developer', 'Data Science', 'Technical PM'],
    difficulty: 'Standard',
    tags: ['Two-column', 'Modern', 'Developer', 'Data Science', 'Dark sidebar'],
    accentColor: '#F97316',
    colorVariants: ['#F97316', '#22D3EE', '#A78BFA', '#34D399']
  },
  {
    id: 'ats-classic',
    name: 'ATS Classic',
    description: 'Two-column, minimal and text-dense with no decorative elements. Perfect for traditional industries or ATS-heavy applications.',
    category: 'ATS',
    previewImage: '/templates/reactive/ats-classic.jpg',
    supportsPhoto: false,
    columns: 2,
    atsFriendly: true,
    supportsSidebar: false,
    sidebarPosition: 'left',
    recommendedFor: ['Traditional', 'ATS', 'Government'],
    difficulty: 'Easy',
    tags: ['Two-column', 'ATS friendly', 'Minimal', 'Text-dense', 'No decoration'],
    accentColor: '#1E293B',
    colorVariants: ['#1E293B', '#2563EB', '#059669', '#7C3AED']
  },
  {
    id: 'business-analyst',
    name: 'Business Analyst',
    description: 'Two-column with accent colors and clean typography. Balanced choice for business analysts or operations roles.',
    category: 'Corporate',
    previewImage: '/templates/reactive/business-analyst.jpg',
    supportsPhoto: false,
    columns: 2,
    atsFriendly: true,
    supportsSidebar: true,
    sidebarPosition: 'left',
    recommendedFor: ['Business Analyst', 'Operations', 'Consulting'],
    difficulty: 'Standard',
    tags: ['Two-column', 'Accent colors', 'Clean typography', 'Business'],
    accentColor: '#7C3AED',
    colorVariants: ['#7C3AED', '#F97316', '#2563EB', '#059669']
  },
  {
    id: 'executive-minimal',
    name: 'Executive Minimal',
    description: 'Two-column with light gray sidebar and subtle styling. Professional and understated for legal, finance, or executive roles.',
    category: 'Executive',
    previewImage: '/templates/reactive/executive-minimal.jpg',
    supportsPhoto: false,
    columns: 2,
    atsFriendly: true,
    supportsSidebar: true,
    sidebarPosition: 'left',
    recommendedFor: ['Legal', 'Finance', 'Executive'],
    difficulty: 'Standard',
    tags: ['Two-column', 'Minimal', 'Professional', 'Legal', 'Executive'],
    accentColor: '#1E293B',
    colorVariants: ['#1E293B', '#2563EB', '#7C3AED', '#059669']
  },
  {
    id: 'compact-entry',
    name: 'Compact Entry',
    description: 'Single-column with a left border accent. Compact and efficient for entry-level or internship applications.',
    category: 'Student',
    previewImage: '/templates/reactive/compact-entry.jpg',
    supportsPhoto: false,
    columns: 1,
    atsFriendly: true,
    supportsSidebar: false,
    sidebarPosition: 'none',
    recommendedFor: ['Entry Level', 'Internship', 'Student'],
    difficulty: 'Easy',
    tags: ['Single-column', 'ATS friendly', 'Compact', 'Entry level', 'Internship'],
    accentColor: '#DC2626',
    colorVariants: ['#DC2626', '#F97316', '#2563EB', '#7C3AED']
  },
  {
    id: 'senior-enterprise',
    name: 'Senior Enterprise',
    description: 'Single-column, polished and serious for senior or enterprise-level positions.',
    category: 'Executive',
    previewImage: '/templates/reactive/senior-enterprise.jpg',
    supportsPhoto: false,
    columns: 1,
    atsFriendly: true,
    supportsSidebar: false,
    sidebarPosition: 'none',
    recommendedFor: ['Senior', 'Enterprise', 'Management'],
    difficulty: 'Standard',
    tags: ['Single-column', 'ATS friendly', 'Polished', 'Senior', 'Enterprise'],
    accentColor: '#2563EB',
    colorVariants: ['#2563EB', '#1E293B', '#7C3AED', '#059669']
  },
  {
    id: 'healthcare-calm',
    name: 'Healthcare Calm',
    description: 'Two-column with a muted earthy right sidebar. Calm aesthetic suits sustainability, healthcare, or nonprofit sectors.',
    category: 'Creative',
    previewImage: '/templates/reactive/healthcare-calm.jpg',
    supportsPhoto: true,
    columns: 2,
    atsFriendly: false,
    supportsSidebar: true,
    sidebarPosition: 'right',
    recommendedFor: ['Healthcare', 'Nonprofit', 'Sustainability'],
    difficulty: 'Standard',
    tags: ['Two-column', 'Earthy', 'Calm', 'Healthcare', 'Nonprofit', 'Photo'],
    accentColor: '#059669',
    colorVariants: ['#059669', '#0D9488', '#2563EB', '#F97316']
  },
  {
    id: 'asia-compact',
    name: 'Asia Compact',
    description: 'Single-column with inline three-column entry headers. Compact and ATS-friendly, suited for Asian resume conventions.',
    category: 'ATS',
    previewImage: '/templates/reactive/asia-compact.jpg',
    supportsPhoto: false,
    columns: 1,
    atsFriendly: true,
    supportsSidebar: false,
    sidebarPosition: 'none',
    recommendedFor: ['Asian Market', 'International', 'ATS'],
    difficulty: 'Easy',
    tags: ['Single-column', 'ATS friendly', 'Inline header', 'Compact', 'Asian style'],
    accentColor: '#1E293B',
    colorVariants: ['#1E293B', '#2563EB', '#059669', '#DC2626']
  },
  {
    id: 'technical-grid',
    name: 'Technical Grid',
    description: 'Single-column with a clean grid layout pairing related sections. Versatile for any professional or technical role.',
    category: 'Tech',
    previewImage: '/templates/reactive/technical-grid.jpg',
    supportsPhoto: false,
    columns: 1,
    atsFriendly: true,
    supportsSidebar: false,
    sidebarPosition: 'none',
    recommendedFor: ['Technical', 'Professional', 'Engineering'],
    difficulty: 'Standard',
    tags: ['Single-column', 'ATS friendly', 'Grid layout', 'Versatile', 'Technical'],
    accentColor: '#F97316',
    colorVariants: ['#F97316', '#2563EB', '#059669', '#7C3AED']
  },
  {
    id: 'accent-column',
    name: 'Accent Column',
    description: 'Two-column with a left accent color strip. Simple and approachable for creative, editorial, or junior roles.',
    category: 'Creative',
    previewImage: '/templates/reactive/accent-column.jpg',
    supportsPhoto: true,
    columns: 2,
    atsFriendly: false,
    supportsSidebar: true,
    sidebarPosition: 'left',
    recommendedFor: ['Creative', 'Editorial', 'Junior'],
    difficulty: 'Easy',
    tags: ['Two-column', 'Simple', 'Creative', 'Editorial', 'Accent strip', 'Photo'],
    accentColor: '#F97316',
    colorVariants: ['#F97316', '#2563EB', '#DC2626', '#059669']
  },
  {
    id: 'whitespace-modern',
    name: 'Whitespace Modern',
    description: 'Single-column with a minimal top header and generous whitespace. Clean and modern for designers or content creators.',
    category: 'Creative',
    previewImage: '/templates/reactive/whitespace-modern.jpg',
    supportsPhoto: false,
    columns: 1,
    atsFriendly: true,
    supportsSidebar: false,
    sidebarPosition: 'none',
    recommendedFor: ['Designer', 'Content Creator', 'UX'],
    difficulty: 'Easy',
    tags: ['Single-column', 'ATS friendly', 'Minimal', 'Clean', 'Modern', 'Whitespace'],
    accentColor: '#1E293B',
    colorVariants: ['#1E293B', '#F97316', '#2563EB', '#7C3AED']
  },
  {
    id: 'executive-bold',
    name: 'Executive Bold',
    description: 'Single-column with uppercase section headings and a primary-color top rule. Polished for executive, consulting, or startup resumes.',
    category: 'Executive',
    previewImage: '/templates/reactive/executive-bold.jpg',
    supportsPhoto: false,
    columns: 1,
    atsFriendly: true,
    supportsSidebar: false,
    sidebarPosition: 'none',
    recommendedFor: ['Executive', 'Consulting', 'Startup'],
    difficulty: 'Standard',
    tags: ['Single-column', 'ATS friendly', 'Uppercase headings', 'Executive', 'Bold'],
    accentColor: '#7C3AED',
    colorVariants: ['#7C3AED', '#F97316', '#2563EB', '#DC2626']
  }
];
