/**
 * OpportunityX Resume — Template Capability System & Metadata Engine
 * Controls feature availability, capabilities, recommendation engine, and metadata normalization across all OpportunityX Original Templates.
 */

import { getTemplatePreviewAsset } from '../assets/templatePreviews';

export const DEFAULT_CAPABILITIES = {
  supportsPhoto: false,
  supportedPhotoPositions: ['top-left', 'top-right', 'center', 'sidebar', 'hidden'],
  supportsSignature: false,
  supportsLogo: false,
  supportsSidebar: false,
  supportsTwoColumns: false,
  supportsAccentBar: true,
  supportsTimeline: false,
  supportsRatingBars: false,
  supportsIcons: true,
  maxPages: 2,
  atsFriendly: true,
  // Future-Ready Capability Architecture
  supportsQRCode: false,
  supportsPortfolio: false,
  supportsSocialCards: false,
  supportsWatermark: false,
  supportsReferences: true,
  supportsCustomHeader: false,
  supportsCustomFooter: false,
  supportsBackgroundPattern: false,
  supportsCharts: false
};

export const STANDARD_ACCENT_COLORS = [
  '#F97316', // OpportunityX Orange
  '#2563EB', // Royal Blue
  '#7C3AED', // Vivid Purple
  '#059669', // Emerald Green
  '#DC2626', // Crimson Red
  '#1E293B', // Classic Slate
  '#0891B2'  // Deep Cyan
];

/**
 * Registry of all unique OpportunityX Original Templates.
 * Each entry maps a distinct layout structure without duplicating color variants.
 */
export const OPPORTUNITYX_TEMPLATES_METADATA = [
  // ─── ATS OPTIMIZED LAYOUTS ───
  {
    id: 'modern',
    name: 'OpportunityX Modern ATS',
    category: 'ATS',
    layoutId: 'layout-ats-01',
    version: '1.2.0',
    author: 'OpportunityX Core',
    license: 'MIT',
    sourceRepository: 'OpportunityX Native Engine',
    statusBadge: 'Recommended',
    atsFriendly: true,
    supportsPhoto: false,
    supportedPhotoPositions: ['hidden'],
    supportsSidebar: false,
    supportsTwoColumns: false,
    supportsAccentBar: true,
    supportsTimeline: false,
    supportsRatingBars: false,
    supportsIcons: true,
    maxPages: 2,
    recommendedExperienceLevel: '0–2 Years',
    recommendedFor: ['Software Engineer', 'Internship', 'Campus Placement', 'General Application'],
    tags: ['ATS', 'Modern', 'Minimal', 'Single-Column', 'High-Contrast'],
    accentColors: STANDARD_ACCENT_COLORS,
    description: 'Single-column high-contrast layout optimized for 100% ATS parser pass rates across Workday, Taleo, and Greenhouse.'
  },
  {
    id: 'minimal',
    name: 'OpportunityX Minimal ATS',
    category: 'ATS',
    layoutId: 'layout-ats-02',
    version: '1.1.0',
    author: 'OpportunityX Core',
    license: 'MIT',
    sourceRepository: 'OpportunityX Native Engine',
    statusBadge: 'Verified',
    atsFriendly: true,
    supportsPhoto: false,
    supportedPhotoPositions: ['hidden'],
    supportsSidebar: false,
    supportsTwoColumns: false,
    supportsAccentBar: false,
    supportsTimeline: false,
    supportsRatingBars: false,
    supportsIcons: false,
    maxPages: 2,
    recommendedExperienceLevel: 'Fresher',
    recommendedFor: ['Legal', 'Finance', 'Traditional Industry', 'Government'],
    tags: ['ATS', 'Minimal', 'Traditional', 'Law', 'Finance'],
    accentColors: STANDARD_ACCENT_COLORS,
    description: 'Ultra-clean minimalist layout suited for traditional corporate, legal, and finance applications.'
  },
  {
    id: 'executive',
    name: 'OpportunityX Executive ATS',
    category: 'Executive',
    layoutId: 'layout-ats-03',
    version: '1.0.0',
    author: 'OpportunityX Core',
    license: 'MIT',
    sourceRepository: 'OpportunityX Native Engine',
    statusBadge: 'Popular',
    atsFriendly: true,
    supportsPhoto: false,
    supportedPhotoPositions: ['hidden'],
    supportsSidebar: false,
    supportsTwoColumns: false,
    supportsAccentBar: true,
    supportsTimeline: false,
    supportsRatingBars: false,
    supportsIcons: true,
    maxPages: 3,
    recommendedExperienceLevel: 'Senior Professional',
    recommendedFor: ['Director', 'VP of Engineering', 'Senior Manager', 'Executive'],
    tags: ['ATS', 'Executive', 'Leadership', 'Management', 'Corporate'],
    accentColors: STANDARD_ACCENT_COLORS,
    description: 'Double-bordered executive layout tailored for senior leadership and management positions.'
  },
  {
    id: 'corporate',
    name: 'OpportunityX Corporate ATS',
    category: 'Business',
    layoutId: 'layout-ats-04',
    version: '1.0.0',
    author: 'OpportunityX Core',
    license: 'MIT',
    sourceRepository: 'OpportunityX Native Engine',
    statusBadge: 'Verified',
    atsFriendly: true,
    supportsPhoto: false,
    supportedPhotoPositions: ['hidden'],
    supportsSidebar: false,
    supportsTwoColumns: false,
    supportsAccentBar: true,
    supportsTimeline: false,
    supportsRatingBars: false,
    supportsIcons: true,
    maxPages: 2,
    recommendedExperienceLevel: '2–5 Years',
    recommendedFor: ['Business Analyst', 'Consultant', 'Project Manager', 'Enterprise Roles'],
    tags: ['ATS', 'Corporate', 'Structured', 'Enterprise'],
    accentColors: STANDARD_ACCENT_COLORS,
    description: 'Structured corporate layout designed for enterprise business roles and consulting applications.'
  },
  {
    id: 'recruiter',
    name: 'OpportunityX Recruiter Scan ATS',
    category: 'ATS',
    layoutId: 'layout-ats-05',
    version: '1.1.0',
    author: 'OpportunityX Core',
    license: 'MIT',
    sourceRepository: 'OpportunityX Native Engine',
    statusBadge: 'Editor\'s Pick',
    atsFriendly: true,
    supportsPhoto: false,
    supportedPhotoPositions: ['hidden'],
    supportsSidebar: false,
    supportsTwoColumns: false,
    supportsAccentBar: true,
    supportsTimeline: false,
    supportsRatingBars: false,
    supportsIcons: true,
    maxPages: 2,
    recommendedExperienceLevel: '0–2 Years',
    recommendedFor: ['High Volume Applicants', 'Tech Applicants', 'Quick Glance Scanning'],
    tags: ['ATS', 'Recruiter Scan', 'High Density', 'Clear Hierarchy'],
    accentColors: STANDARD_ACCENT_COLORS,
    description: 'Engineered specifically for 6-second recruiter glance scanning with bold section headers.'
  },
  {
    id: 'fullstack',
    name: 'OpportunityX Tech Stack',
    category: 'Tech',
    layoutId: 'layout-tech-01',
    version: '1.3.0',
    author: 'OpportunityX Core',
    license: 'MIT',
    sourceRepository: 'OpportunityX Native Engine',
    statusBadge: 'Popular',
    atsFriendly: true,
    supportsPhoto: false,
    supportedPhotoPositions: ['hidden'],
    supportsSidebar: false,
    supportsTwoColumns: false,
    supportsAccentBar: true,
    supportsTimeline: false,
    supportsRatingBars: false,
    supportsIcons: true,
    maxPages: 2,
    recommendedExperienceLevel: '0–2 Years',
    recommendedFor: ['Full Stack Engineer', 'Backend Developer', 'Frontend Developer', 'DevOps'],
    tags: ['Tech', 'Developer', 'Code Badges', 'GitHub', 'Tech Stack'],
    accentColors: STANDARD_ACCENT_COLORS,
    description: 'Displays tech stack tags, repository metrics, and system architecture accomplishments clearly.'
  },

  // ─── CREATIVE & SIDEBAR LAYOUTS (PHOTO SUPPORTED) ───
  {
    id: 'creative-sidebar',
    name: 'OpportunityX Creative Sidebar',
    category: 'Creative',
    layoutId: 'layout-creative-01',
    version: '2.0.0',
    author: 'OpportunityX Adapted (Reactive Reference)',
    license: 'MIT',
    sourceRepository: 'Reactive Resume (Azurill)',
    statusBadge: 'Recommended',
    atsFriendly: false,
    supportsPhoto: true,
    supportedPhotoPositions: ['sidebar', 'top-left', 'hidden'],
    supportsSidebar: true,
    supportsTwoColumns: true,
    supportsAccentBar: true,
    supportsTimeline: false,
    supportsRatingBars: true,
    supportsIcons: true,
    maxPages: 3,
    recommendedExperienceLevel: '2–5 Years',
    recommendedFor: ['UI/UX Designer', 'Creative Director', 'Tech Lead', 'Product Manager'],
    tags: ['Creative', 'Sidebar', 'Two-Column', 'Photo', 'Skill Ratings'],
    accentColors: STANDARD_ACCENT_COLORS,
    description: 'Two-column layout with a bold left accent sidebar, skill rating bars, and profile photo support.'
  },
  {
    id: 'marketing-accent',
    name: 'OpportunityX Marketing Accent',
    category: 'Creative',
    layoutId: 'layout-creative-02',
    version: '1.2.0',
    author: 'OpportunityX Adapted (Reactive Reference)',
    license: 'MIT',
    sourceRepository: 'Reactive Resume (Chikorita)',
    statusBadge: 'Popular',
    atsFriendly: false,
    supportsPhoto: true,
    supportedPhotoPositions: ['top-right', 'top-left', 'sidebar', 'hidden'],
    supportsSidebar: true,
    supportsTwoColumns: true,
    supportsAccentBar: true,
    supportsTimeline: false,
    supportsRatingBars: false,
    supportsIcons: true,
    maxPages: 3,
    recommendedExperienceLevel: '0–2 Years',
    recommendedFor: ['Marketing Specialist', 'HR Manager', 'Client Relations', 'Sales Lead'],
    tags: ['Marketing', 'Soft Accent', 'Photo', 'Right Sidebar', 'Two-Column'],
    accentColors: STANDARD_ACCENT_COLORS,
    description: 'Soft header accent with right column sidebar and circular headshot framing.'
  },
  {
    id: 'developer-dark',
    name: 'OpportunityX Developer Pro',
    category: 'Tech',
    layoutId: 'layout-tech-02',
    version: '1.5.0',
    author: 'OpportunityX Adapted (Reactive Reference)',
    license: 'MIT',
    sourceRepository: 'Reactive Resume (Gengar)',
    statusBadge: 'Community Favorite',
    atsFriendly: false,
    supportsPhoto: false,
    supportedPhotoPositions: ['hidden'],
    supportsSidebar: true,
    supportsTwoColumns: true,
    supportsAccentBar: true,
    supportsTimeline: false,
    supportsRatingBars: false,
    supportsIcons: true,
    maxPages: 3,
    recommendedExperienceLevel: '2–5 Years',
    recommendedFor: ['Software Architect', 'Data Scientist', 'Technical PM', 'AI Engineer'],
    tags: ['Developer', 'Dark Sidebar', 'Technical Grid', 'Two-Column'],
    accentColors: STANDARD_ACCENT_COLORS,
    description: 'Dark sidebar contrast paired with clean technical grids for software engineers and data leads.'
  },
  {
    id: 'ats-classic',
    name: 'OpportunityX Two-Column Classic',
    category: 'ATS',
    layoutId: 'layout-ats-06',
    version: '1.0.0',
    author: 'OpportunityX Adapted (Reactive Reference)',
    license: 'MIT',
    sourceRepository: 'Reactive Resume (Kakuna)',
    statusBadge: 'Verified',
    atsFriendly: true,
    supportsPhoto: false,
    supportedPhotoPositions: ['hidden'],
    supportsSidebar: false,
    supportsTwoColumns: true,
    supportsAccentBar: false,
    supportsTimeline: false,
    supportsRatingBars: false,
    supportsIcons: false,
    maxPages: 2,
    recommendedExperienceLevel: '0–2 Years',
    recommendedFor: ['Government', 'Traditional Corporate', 'Academic', 'High Compliance'],
    tags: ['ATS', 'Two-Column', 'Minimal', 'Dense Text', 'No Decoration'],
    accentColors: STANDARD_ACCENT_COLORS,
    description: 'Minimal two-column layout with high text density and unadorned typography.'
  },
  {
    id: 'business-analyst',
    name: 'OpportunityX Business Analyst',
    category: 'Business',
    layoutId: 'layout-biz-01',
    version: '1.1.0',
    author: 'OpportunityX Adapted (Reactive Reference)',
    license: 'MIT',
    sourceRepository: 'Reactive Resume (Pikachu)',
    statusBadge: 'Verified',
    atsFriendly: true,
    supportsPhoto: false,
    supportedPhotoPositions: ['hidden'],
    supportsSidebar: true,
    supportsTwoColumns: true,
    supportsAccentBar: true,
    supportsTimeline: false,
    supportsRatingBars: false,
    supportsIcons: true,
    maxPages: 2,
    recommendedExperienceLevel: '2–5 Years',
    recommendedFor: ['Business Analyst', 'Operations Lead', 'Consultant', 'Financial Analyst'],
    tags: ['Business', 'Analyst', 'Two-Column', 'Clean Dividers'],
    accentColors: STANDARD_ACCENT_COLORS,
    description: 'Balanced two-column layout with clean section dividers and subtle accent accents.'
  },
  {
    id: 'executive-minimal',
    name: 'OpportunityX Executive Minimal',
    category: 'Executive',
    layoutId: 'layout-exec-01',
    version: '1.0.0',
    author: 'OpportunityX Adapted (Reactive Reference)',
    license: 'MIT',
    sourceRepository: 'Reactive Resume (Ninetales)',
    statusBadge: 'Verified',
    atsFriendly: true,
    supportsPhoto: false,
    supportedPhotoPositions: ['hidden'],
    supportsSidebar: true,
    supportsTwoColumns: true,
    supportsAccentBar: true,
    supportsTimeline: false,
    supportsRatingBars: false,
    supportsIcons: true,
    maxPages: 2,
    recommendedExperienceLevel: 'Senior Professional',
    recommendedFor: ['Executive', 'Legal Counsel', 'Managing Director', 'Board Advisor'],
    tags: ['Executive', 'Minimal', 'Gray Sidebar', 'Understated'],
    accentColors: STANDARD_ACCENT_COLORS,
    description: 'Understated executive template featuring a soft gray sidebar and premium serif-like structure.'
  },
  {
    id: 'compact-entry',
    name: 'OpportunityX Compact Entry',
    category: 'Student',
    layoutId: 'layout-student-01',
    version: '1.0.0',
    author: 'OpportunityX Adapted (Reactive Reference)',
    license: 'MIT',
    sourceRepository: 'Reactive Resume (Leafish)',
    statusBadge: 'Popular',
    atsFriendly: true,
    supportsPhoto: false,
    supportedPhotoPositions: ['hidden'],
    supportsSidebar: false,
    supportsTwoColumns: false,
    supportsAccentBar: true,
    supportsTimeline: false,
    supportsRatingBars: false,
    supportsIcons: true,
    maxPages: 1,
    recommendedExperienceLevel: 'Student',
    recommendedFor: ['Internship', 'Fresh Graduate', 'Entry Level', 'Campus Hire'],
    tags: ['Student', 'Compact', 'Single-Page', 'Border Accent'],
    accentColors: STANDARD_ACCENT_COLORS,
    description: 'Designed specifically to fit early career experience and projects into a crisp 1-page layout.'
  },
  {
    id: 'senior-enterprise',
    name: 'OpportunityX Senior Enterprise',
    category: 'Executive',
    layoutId: 'layout-exec-02',
    version: '1.1.0',
    author: 'OpportunityX Adapted (Reactive Reference)',
    license: 'MIT',
    sourceRepository: 'Reactive Resume (Charizard)',
    statusBadge: 'Verified',
    atsFriendly: true,
    supportsPhoto: false,
    supportedPhotoPositions: ['hidden'],
    supportsSidebar: false,
    supportsTwoColumns: false,
    supportsAccentBar: true,
    supportsTimeline: false,
    supportsRatingBars: false,
    supportsIcons: true,
    maxPages: 3,
    recommendedExperienceLevel: 'Senior Professional',
    recommendedFor: ['VP', 'Senior Director', 'Enterprise Lead', 'Principal Consultant'],
    tags: ['Enterprise', 'Senior', 'Polished', 'Single-Column'],
    accentColors: STANDARD_ACCENT_COLORS,
    description: 'Polished single-column design tailored for senior leaders with extensive career history.'
  },
  {
    id: 'healthcare-calm',
    name: 'OpportunityX Healthcare Calm',
    category: 'Academic',
    layoutId: 'layout-acad-01',
    version: '1.0.0',
    author: 'OpportunityX Adapted (Reactive Reference)',
    license: 'MIT',
    sourceRepository: 'Reactive Resume (Eevee)',
    statusBadge: 'Verified',
    atsFriendly: true,
    supportsPhoto: true,
    supportedPhotoPositions: ['sidebar', 'top-right', 'hidden'],
    supportsSidebar: true,
    supportsTwoColumns: true,
    supportsAccentBar: true,
    supportsTimeline: false,
    supportsRatingBars: false,
    supportsIcons: true,
    maxPages: 3,
    recommendedExperienceLevel: '2–5 Years',
    recommendedFor: ['Healthcare', 'Clinical', 'Nonprofit', 'Sustainability Specialist'],
    tags: ['Healthcare', 'Calm', 'Earthy', 'Sidebar', 'Photo'],
    accentColors: STANDARD_ACCENT_COLORS,
    description: 'Calm aesthetic with muted sidebar tones suitable for medical, sustainability, and human services.'
  },
  {
    id: 'asia-compact',
    name: 'OpportunityX Global Compact',
    category: 'ATS',
    layoutId: 'layout-ats-07',
    version: '1.0.0',
    author: 'OpportunityX Adapted (Reactive Reference)',
    license: 'MIT',
    sourceRepository: 'Reactive Resume (Ditto)',
    statusBadge: 'Verified',
    atsFriendly: true,
    supportsPhoto: false,
    supportedPhotoPositions: ['hidden'],
    supportsSidebar: false,
    supportsTwoColumns: false,
    supportsAccentBar: true,
    supportsTimeline: false,
    supportsRatingBars: false,
    supportsIcons: false,
    maxPages: 2,
    recommendedExperienceLevel: '0–2 Years',
    recommendedFor: ['Asian Market', 'Global Applicant', 'International Placement'],
    tags: ['Global', 'Compact', 'Inline Header', 'ATS'],
    accentColors: STANDARD_ACCENT_COLORS,
    description: 'Features inline entry headers adhering to international application conventions.'
  },
  {
    id: 'technical-grid',
    name: 'OpportunityX Technical Grid',
    category: 'Tech',
    layoutId: 'layout-tech-03',
    version: '1.2.0',
    author: 'OpportunityX Adapted (Reactive Reference)',
    license: 'MIT',
    sourceRepository: 'Reactive Resume (Onix)',
    statusBadge: 'Recommended',
    atsFriendly: true,
    supportsPhoto: false,
    supportedPhotoPositions: ['hidden'],
    supportsSidebar: false,
    supportsTwoColumns: false,
    supportsAccentBar: true,
    supportsTimeline: false,
    supportsRatingBars: false,
    supportsIcons: true,
    maxPages: 2,
    recommendedExperienceLevel: '0–2 Years',
    recommendedFor: ['Software Engineer', 'Systems Engineer', 'QA Engineer'],
    tags: ['Technical', 'Grid', 'Clean Layout', 'ATS'],
    accentColors: STANDARD_ACCENT_COLORS,
    description: 'Clean structured grid layout highlighting technical skill competencies alongside experience.'
  },
  {
    id: 'accent-column',
    name: 'OpportunityX Accent Column',
    category: 'Creative',
    layoutId: 'layout-creative-03',
    version: '1.0.0',
    author: 'OpportunityX Adapted (Reactive Reference)',
    license: 'MIT',
    sourceRepository: 'Reactive Resume (Snorlax)',
    statusBadge: 'Verified',
    atsFriendly: false,
    supportsPhoto: true,
    supportedPhotoPositions: ['sidebar', 'top-left', 'hidden'],
    supportsSidebar: true,
    supportsTwoColumns: true,
    supportsAccentBar: true,
    supportsTimeline: false,
    supportsRatingBars: false,
    supportsIcons: true,
    maxPages: 3,
    recommendedExperienceLevel: '0–2 Years',
    recommendedFor: ['Creative Writer', 'Editorial', 'Junior Designer', 'Content Manager'],
    tags: ['Creative', 'Accent Strip', 'Photo', 'Two-Column'],
    accentColors: STANDARD_ACCENT_COLORS,
    description: 'Left vertical accent strip paired with headshot framing for editorial and creative professionals.'
  },
  {
    id: 'whitespace-modern',
    name: 'OpportunityX Whitespace Modern',
    category: 'Creative',
    layoutId: 'layout-creative-04',
    version: '1.1.0',
    author: 'OpportunityX Adapted (Reactive Reference)',
    license: 'MIT',
    sourceRepository: 'Reactive Resume (Vulpix)',
    statusBadge: 'Verified',
    atsFriendly: true,
    supportsPhoto: false,
    supportedPhotoPositions: ['hidden'],
    supportsSidebar: false,
    supportsTwoColumns: false,
    supportsAccentBar: true,
    supportsTimeline: false,
    supportsRatingBars: false,
    supportsIcons: false,
    maxPages: 2,
    recommendedExperienceLevel: '0–2 Years',
    recommendedFor: ['UX Writer', 'Content Strategist', 'Minimalist Designer'],
    tags: ['Minimal', 'Whitespace', 'Clean', 'Modern'],
    accentColors: STANDARD_ACCENT_COLORS,
    description: 'Emphasizes typography hierarchy and generous padding for high readability.'
  },
  {
    id: 'executive-bold',
    name: 'OpportunityX Executive Bold',
    category: 'Executive',
    layoutId: 'layout-exec-03',
    version: '1.0.0',
    author: 'OpportunityX Adapted (Reactive Reference)',
    license: 'MIT',
    sourceRepository: 'Reactive Resume (Mewtwo)',
    statusBadge: 'Editor\'s Pick',
    atsFriendly: true,
    supportsPhoto: false,
    supportedPhotoPositions: ['hidden'],
    supportsSidebar: false,
    supportsTwoColumns: false,
    supportsAccentBar: true,
    supportsTimeline: false,
    supportsRatingBars: false,
    supportsIcons: true,
    maxPages: 2,
    recommendedExperienceLevel: 'Senior Professional',
    recommendedFor: ['Startup Founder', 'Managing Consultant', 'Head of Product'],
    tags: ['Executive', 'Bold Headings', 'Uppercase', 'Single-Column'],
    accentColors: STANDARD_ACCENT_COLORS,
    description: 'Prominent uppercase headings with top primary accent rules for impactful executive presentations.'
  },

  // ─── BEST RESUME EVER LAYOUTS (PHOTO SUPPORTED) ───
  {
    id: 'bre-cool',
    name: 'OpportunityX Banner Pro',
    category: 'Creative',
    layoutId: 'layout-bre-01',
    version: '1.2.0',
    author: 'OpportunityX Adapted (Best-Resume-Ever Reference)',
    license: 'MIT',
    sourceRepository: 'Best-Resume-Ever (Cool Banner)',
    statusBadge: 'Popular',
    atsFriendly: false,
    supportsPhoto: true,
    supportedPhotoPositions: ['top-right', 'sidebar', 'top-left', 'hidden'],
    supportsSidebar: true,
    supportsTwoColumns: true,
    supportsAccentBar: true,
    supportsTimeline: false,
    supportsRatingBars: true,
    supportsIcons: true,
    maxPages: 3,
    recommendedExperienceLevel: '2–5 Years',
    recommendedFor: ['Startup Lead', 'Product Manager', 'Tech Entrepreneur'],
    tags: ['Top Banner', 'Dark Sidebar', 'Photo', 'Creative'],
    accentColors: STANDARD_ACCENT_COLORS,
    description: 'Top colored header banner combined with dark sidebar navigation and headshot container.'
  },
  {
    id: 'bre-creative',
    name: 'OpportunityX Creative Top Accent',
    category: 'Creative',
    layoutId: 'layout-bre-02',
    version: '1.0.0',
    author: 'OpportunityX Adapted (Best-Resume-Ever Reference)',
    license: 'MIT',
    sourceRepository: 'Best-Resume-Ever (Creative)',
    statusBadge: 'Verified',
    atsFriendly: false,
    supportsPhoto: true,
    supportedPhotoPositions: ['top-left', 'top-right', 'hidden'],
    supportsSidebar: true,
    supportsTwoColumns: true,
    supportsAccentBar: true,
    supportsTimeline: false,
    supportsRatingBars: false,
    supportsIcons: true,
    maxPages: 3,
    recommendedExperienceLevel: '0–2 Years',
    recommendedFor: ['Graphic Designer', 'Front-End Developer', 'Animator'],
    tags: ['Creative', 'Header Accent', 'Photo', 'Two-Column'],
    accentColors: STANDARD_ACCENT_COLORS,
    description: 'Header accent line styling with structured two-column content organization.'
  },
  {
    id: 'bre-green',
    name: 'OpportunityX Accent Header',
    category: 'ATS',
    layoutId: 'layout-bre-03',
    version: '1.1.0',
    author: 'OpportunityX Adapted (Best-Resume-Ever Reference)',
    license: 'MIT',
    sourceRepository: 'Best-Resume-Ever (Green & Purple Unified)',
    statusBadge: 'Verified',
    atsFriendly: true,
    supportsPhoto: true,
    supportedPhotoPositions: ['top-right', 'top-left', 'center', 'hidden'],
    supportsSidebar: false,
    supportsTwoColumns: false,
    supportsAccentBar: true,
    supportsTimeline: false,
    supportsRatingBars: false,
    supportsIcons: true,
    maxPages: 2,
    recommendedExperienceLevel: '0–2 Years',
    recommendedFor: ['General Applicants', 'Consultants', 'Analysts'],
    tags: ['Header Border', 'Clean', 'Photo Optional', 'Unified Layout'],
    accentColors: STANDARD_ACCENT_COLORS,
    description: 'Clean horizontal header border layout with optional right headshot alignment.'
  },
  {
    id: 'bre-left-right',
    name: 'OpportunityX Left-Right Split',
    category: 'Creative',
    layoutId: 'layout-bre-04',
    version: '1.0.0',
    author: 'OpportunityX Adapted (Best-Resume-Ever Reference)',
    license: 'MIT',
    sourceRepository: 'Best-Resume-Ever (Left-Right)',
    statusBadge: 'Verified',
    atsFriendly: false,
    supportsPhoto: true,
    supportedPhotoPositions: ['top-left', 'sidebar', 'hidden'],
    supportsSidebar: true,
    supportsTwoColumns: true,
    supportsAccentBar: true,
    supportsTimeline: false,
    supportsRatingBars: false,
    supportsIcons: true,
    maxPages: 3,
    recommendedExperienceLevel: '2–5 Years',
    recommendedFor: ['Architect', 'Interior Designer', 'Photographer'],
    tags: ['Split Layout', 'Photo', 'Creative', 'Two-Column'],
    accentColors: STANDARD_ACCENT_COLORS,
    description: 'Balanced 50/50 split layout dividing contact info and experience into distinct panels.'
  },
  {
    id: 'bre-material-dark',
    name: 'OpportunityX Material Dark',
    category: 'Tech',
    layoutId: 'layout-bre-05',
    version: '1.1.0',
    author: 'OpportunityX Adapted (Best-Resume-Ever Reference)',
    license: 'MIT',
    sourceRepository: 'Best-Resume-Ever (Material Dark)',
    statusBadge: 'Popular',
    atsFriendly: false,
    supportsPhoto: true,
    supportedPhotoPositions: ['sidebar', 'top-left', 'hidden'],
    supportsSidebar: true,
    supportsTwoColumns: true,
    supportsAccentBar: true,
    supportsTimeline: false,
    supportsRatingBars: true,
    supportsIcons: true,
    maxPages: 3,
    recommendedExperienceLevel: '2–5 Years',
    recommendedFor: ['Game Developer', 'Cybersecurity Specialist', 'System Admin'],
    tags: ['Material Dark', 'Teal Contrast', 'Photo', 'Tech'],
    accentColors: STANDARD_ACCENT_COLORS,
    description: 'Material design inspired dark sidebar with high contrast section cards.'
  },
  {
    id: 'bre-oblique',
    name: 'OpportunityX Oblique Dynamic',
    category: 'Creative',
    layoutId: 'layout-bre-06',
    version: '1.0.0',
    author: 'OpportunityX Adapted (Best-Resume-Ever Reference)',
    license: 'MIT',
    sourceRepository: 'Best-Resume-Ever (Oblique)',
    statusBadge: 'Verified',
    atsFriendly: false,
    supportsPhoto: true,
    supportedPhotoPositions: ['top-right', 'sidebar', 'hidden'],
    supportsSidebar: true,
    supportsTwoColumns: true,
    supportsAccentBar: true,
    supportsTimeline: false,
    supportsRatingBars: false,
    supportsIcons: true,
    maxPages: 3,
    recommendedExperienceLevel: '0–2 Years',
    recommendedFor: ['Event Manager', 'Publicist', 'Media Producer'],
    tags: ['Oblique', 'Angled Header', 'Creative', 'Photo'],
    accentColors: STANDARD_ACCENT_COLORS,
    description: 'Modern angled visual dividers providing dynamic flair for media and communications.'
  },
  {
    id: 'bre-sidebar',
    name: 'OpportunityX Professional Sidebar',
    category: 'Business',
    layoutId: 'layout-bre-07',
    version: '1.2.0',
    author: 'OpportunityX Adapted (Best-Resume-Ever Reference)',
    license: 'MIT',
    sourceRepository: 'Best-Resume-Ever (Sidebar)',
    statusBadge: 'Recommended',
    atsFriendly: false,
    supportsPhoto: true,
    supportedPhotoPositions: ['sidebar', 'top-left', 'hidden'],
    supportsSidebar: true,
    supportsTwoColumns: true,
    supportsAccentBar: true,
    supportsTimeline: false,
    supportsRatingBars: false,
    supportsIcons: true,
    maxPages: 3,
    recommendedExperienceLevel: '2–5 Years',
    recommendedFor: ['Corporate Communications', 'Brand Specialist', 'Sales Manager'],
    tags: ['Sidebar', 'Photo', 'Corporate', 'Two-Column'],
    accentColors: STANDARD_ACCENT_COLORS,
    description: 'Full-height left sidebar separating core profile metadata from experience details.'
  },
  {
    id: 'jsonresume-modern',
    name: 'OpportunityX Standard Modern',
    category: 'ATS',
    layoutId: 'layout-json-01',
    version: '1.0.0',
    author: 'OpportunityX Adapted (JSONResume Reference)',
    license: 'MIT',
    sourceRepository: 'JSONResume Modern Theme',
    statusBadge: 'Verified',
    atsFriendly: true,
    supportsPhoto: true,
    supportedPhotoPositions: ['top-left', 'top-right', 'sidebar', 'hidden'],
    supportsSidebar: true,
    supportsTwoColumns: true,
    supportsAccentBar: true,
    supportsTimeline: false,
    supportsRatingBars: false,
    supportsIcons: true,
    maxPages: 3,
    recommendedExperienceLevel: '0–2 Years',
    recommendedFor: ['Open Source Contributor', 'Software Developer', 'Tech Generalist'],
    tags: ['JSONResume', 'Modern', 'Standard Schema', 'Photo'],
    accentColors: STANDARD_ACCENT_COLORS,
    description: 'Adapted directly from JSONResume modern spec with complete schema field support.'
  }
];

/**
 * Normalizes template metadata by merging with DEFAULT_CAPABILITIES.
 * Attaches standardized preview object { thumbnail, normal, full }.
 */
export const getTemplateCapabilities = (templateId) => {
  const targetId = templateId || 'modern';
  const found = OPPORTUNITYX_TEMPLATES_METADATA.find((t) => t.id === targetId || t.layoutId === targetId);

  const base = found || {
    id: targetId,
    name: 'OpportunityX Resume',
    category: 'ATS',
    layoutId: 'layout-custom',
    ...DEFAULT_CAPABILITIES,
    accentColors: STANDARD_ACCENT_COLORS
  };

  return {
    ...DEFAULT_CAPABILITIES,
    ...base,
    preview: {
      thumbnail: getTemplatePreviewAsset(targetId, 'thumbnail'),
      normal: getTemplatePreviewAsset(targetId, 'normal'),
      full: getTemplatePreviewAsset(targetId, 'full')
    }
  };
};

/**
 * Evaluates whether a specific template supports a given capability key.
 */
export const hasCapability = (templateId, capabilityKey) => {
  const caps = getTemplateCapabilities(templateId);
  return Boolean(caps[capabilityKey]);
};

/**
 * Returns supported photo positions for a template.
 */
export const getSupportedPhotoPositions = (templateId) => {
  const caps = getTemplateCapabilities(templateId);
  return caps.supportedPhotoPositions || ['hidden'];
};

/**
 * Returns template recommendations based on candidate's target job title / profile.
 */
export const getRecommendedTemplates = (jobTitle = '') => {
  const titleLower = (jobTitle || '').toLowerCase();

  if (titleLower.includes('developer') || titleLower.includes('engineer') || titleLower.includes('tech') || titleLower.includes('code')) {
    return ['fullstack', 'developer-dark', 'technical-grid', 'modern'];
  }
  if (titleLower.includes('design') || titleLower.includes('creative') || titleLower.includes('ux') || titleLower.includes('art')) {
    return ['creative-sidebar', 'marketing-accent', 'accent-column', 'whitespace-modern'];
  }
  if (titleLower.includes('executive') || titleLower.includes('director') || titleLower.includes('vp') || titleLower.includes('manager')) {
    return ['executive', 'executive-minimal', 'senior-enterprise', 'executive-bold'];
  }
  if (titleLower.includes('student') || titleLower.includes('intern') || titleLower.includes('fresher') || titleLower.includes('graduate')) {
    return ['compact-entry', 'minimal', 'modern', 'recruiter'];
  }
  if (titleLower.includes('business') || titleLower.includes('analyst') || titleLower.includes('consultant') || titleLower.includes('finance')) {
    return ['business-analyst', 'corporate', 'bre-sidebar', 'ats-classic'];
  }
  if (titleLower.includes('health') || titleLower.includes('doctor') || titleLower.includes('nurse') || titleLower.includes('bio')) {
    return ['healthcare-calm', 'minimal', 'bre-green'];
  }

  // Default recommendations
  return ['modern', 'creative-sidebar', 'fullstack', 'executive'];
};
